# Generated by Django 3.2.5 on 2021-08-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('estrategia', models.TextField(verbose_name='Estrategia')),
                ('problematica', models.TextField(verbose_name='Problematica')),
            ],
            options={
                'verbose_name': 'Eje',
                'verbose_name_plural': 'Ejes',
            },
        ),
        migrations.CreateModel(
            name='FactorDesagregacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Factor Desagregacion',
                'verbose_name_plural': 'Factores Desagregacion',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
                ('alcance', models.IntegerField(blank=True, choices=[(1, 'Corto'), (2, 'Medio'), (3, 'Largo')], null=True, verbose_name='Alcance')),
                ('periodicidad', models.IntegerField(blank=True, choices=[(1, 'Anual'), (2, 'Semestral'), (3, 'Cuatrimestral'), (4, 'Trimestral'), (5, 'Mensual')], null=True, verbose_name='Periodicidad de medicion')),
                ('fuente_verificacion', models.TextField(verbose_name='Fuente de Verificacion')),
                ('notas', models.TextField(verbose_name='Notas Tecnicas')),
                ('informacion_requerida', models.TextField(verbose_name='Informacion a Requerir')),
                ('factores_desagregacion', models.ManyToManyField(related_name='indicadores', to='visor.FactorDesagregacion')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('tipo', models.IntegerField(choices=[(1, 'Cualitativo'), (2, 'Cuantitativo')], default=1, verbose_name='Tipo')),
                ('indicador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='visor.indicador')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='ValorFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=150, verbose_name='Valor')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.factordesagregacion')),
            ],
            options={
                'verbose_name': 'Valor Factor',
                'verbose_name_plural': 'Valores Factor',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Simbolo')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.variable')),
            ],
            options={
                'verbose_name': 'Unidad edida',
                'verbose_name_plural': 'Unidades Medida',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('resultado', models.TextField(verbose_name='Resultado')),
                ('presupuesto', models.TextField(verbose_name='Presupuesto')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visor.eje')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='visor.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='MedicionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('valor_medicion', models.CharField(max_length=50, verbose_name='Codigo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='visor.area')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='visor.indicador')),
                ('valores_factor', models.ManyToManyField(to='visor.ValorFactor')),
            ],
            options={
                'verbose_name': 'Medicion de Indicador',
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='fuentes_informacion',
            field=models.ManyToManyField(related_name='indicadores_fuentes', to='visor.Institucion'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='instituciones',
            field=models.ManyToManyField(related_name='indicadores', to='visor.Institucion'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='visor.resultado'),
        ),
        migrations.AddField(
            model_name='area',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='visor.municipio'),
        ),
    ]
