# Generated by Django 3.2.5 on 2021-08-11 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionindicador',
            name='valor_etario_final',
            field=models.IntegerField(default=None, verbose_name='Valor Etario Final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicionindicador',
            name='valor_etario_inicial',
            field=models.IntegerField(default=None, verbose_name='Valor Etario Inicial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='area',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='visor.municipio'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='estrategia',
            field=models.TextField(blank=True, null=True, verbose_name='Estrategia'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='problematica',
            field=models.TextField(blank=True, null=True, verbose_name='Problematica'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='factores_desagregacion',
            field=models.ManyToManyField(blank=True, null=True, related_name='indicadores', to='visor.FactorDesagregacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuente_verificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Fuente de Verificacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuentes_informacion',
            field=models.ManyToManyField(blank=True, null=True, related_name='indicadores_fuentes', to='visor.Institucion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='informacion_requerida',
            field=models.TextField(blank=True, null=True, verbose_name='Informacion a Requerir'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='instituciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='indicadores', to='visor.Institucion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Tecnicas'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='visor.departamento'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visor.eje'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='presupuesto',
            field=models.TextField(blank=True, null=True, verbose_name='Presupuesto'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='simbolo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Simbolo'),
        ),
        migrations.AlterField(
            model_name='valorfactor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visor.factordesagregacion'),
        ),
        migrations.AlterField(
            model_name='valorfactor',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='valorfactor',
            name='valor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Valor'),
        ),
    ]
