# Generated by Django 3.2.5 on 2021-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_auto_20210811_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='factores_desagregacion',
            field=models.ManyToManyField(related_name='indicadores', to='visor.FactorDesagregacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuentes_informacion',
            field=models.ManyToManyField(related_name='indicadores_fuentes', to='visor.Institucion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='instituciones',
            field=models.ManyToManyField(related_name='indicadores', to='visor.Institucion'),
        ),
    ]
