# Generated by Django 3.2.5 on 2021-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0003_auto_20210811_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='Formula'),
        ),
    ]
