# Generated by Django 3.2.5 on 2021-08-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0004_indicador_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Fuente de Informacion',
                'verbose_name_plural': 'Fuentes de Informacion',
            },
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuentes_informacion',
            field=models.ManyToManyField(related_name='indicadores', to='visor.FuenteInformacion'),
        ),
    ]
