# Generated by Django 3.2.5 on 2021-08-14 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0006_auto_20210814_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmedida',
            name='variable',
        ),
        migrations.AddField(
            model_name='variable',
            name='unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variable', to='visor.unidadmedida'),
            preserve_default=False,
        ),
    ]
