# Generated by Django 3.2.5 on 2021-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0009_alter_valorfactor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicionindicador',
            name='valor_etario_final',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Etario Final'),
        ),
        migrations.AlterField(
            model_name='medicionindicador',
            name='valor_etario_inicial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor Etario Inicial'),
        ),
        migrations.AlterField(
            model_name='medicionindicador',
            name='valor_medicion',
            field=models.CharField(max_length=50, verbose_name='Valor de Medicion'),
        ),
    ]
