# Generated by Django 3.2.5 on 2021-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0010_auto_20210830_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionindicador',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
