# Generated by Django 3.2.5 on 2021-09-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0012_auto_20210909_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionindicador',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='visor.institucion'),
        ),
    ]
