# Generated by Django 3.2.5 on 2021-09-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0015_auto_20210916_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='factores_desagregacion',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='visor.FactorDesagregacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='fuentes_informacion',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='visor.FuenteInformacion'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='instituciones',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='visor.Institucion'),
        ),
    ]
