# Generated by Django 3.2.5 on 2021-10-05 20:24

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0017_indicador_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='archivo',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=pathlib.PurePosixPath('/home/roma/Django/spass/visorspass/mediciones'), verbose_name='Archivo'),
        ),
    ]
