# Generated by Django 3.2.5 on 2021-10-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0018_indicador_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionindicador',
            name='ano',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='archivo',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='mediciones/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='medicionindicador',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
