# Generated by Django 3.2.5 on 2021-10-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0019_auto_20211019_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentoss',
            },
        ),
        migrations.AlterField(
            model_name='indicador',
            name='archivo',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='documentos/', verbose_name='Archivo Ficha'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='visor.eje'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='visor.Documento'),
        ),
    ]
