# Generated by Django 3.2.5 on 2021-11-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0021_documento_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicionindicador',
            name='valor_etario_final',
        ),
        migrations.RemoveField(
            model_name='medicionindicador',
            name='valor_etario_inicial',
        ),
    ]
