# Generated by Django 3.2.5 on 2021-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0022_auto_20211111_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
    ]
