# Generated by Django 3.2.5 on 2022-03-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0025_reporteanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='indicador_general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subindicadores', to='visor.indicador'),
        ),
    ]
