# Generated by Django 3.2.5 on 2022-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0026_indicador_indicador_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='subtitulo',
            field=models.CharField(blank=True, default='', max_length=350, null=True, verbose_name='Subtitulo'),
        ),
    ]
